name: NKpickup
main: be.noki_senpai.NKpickup.NKpickup
version: 1.0.0
api-version: 1.14
author: 'NoKi_senpai'
description: 'Allows players to cancel pickup of a items/blocks list'
website: www.lumen.ovh
commands:
  nopickup:
    description: "Add an item/block to blacklist"
    usage: /<command> <item_name>
  pickup:
    description: "Add an item/block to whitelist"
    usage: /<command> <item_name>
  pickupreset:
    description: "Reset blacklist and whitelist"
    usage: /<command>